# Generated by Django 5.0.9 on 2024-11-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_archivespage'),
        ('postline', '0002_extendedarticlepage_delete_postlinepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtendedArticlePage',
            new_name='PostlineIndexPage',
        ),
    ]
