# Generated by Django 5.0.9 on 2024-11-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postline', '0005_createpostpage_delete_postlinepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePostPage',
        ),
    ]
