# Generated by Django 5.0.9 on 2024-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postline', '0007_postlinepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlinepage',
            name='image',
            field=models.ImageField(blank=True, help_text='Generated image for the Instagram post.', null=True, upload_to='instagram_posts/'),
        ),
    ]
