# Generated by Django 5.0.9 on 2024-11-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postline', '0008_postlinepage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostlineIndexPage',
        ),
    ]
