# Generated by Django 2.0.7 on 2018-07-10 01:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("articles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="headline",
            field=wagtail.core.fields.RichTextField(default="hi"),
            preserve_default=False,
        )
    ]
