# Generated by Django 2.0.8 on 2018-08-31 17:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0001_initial"), ("articles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="featured_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown at the top of the article and on the home page.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Photo",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="kicker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="articles.Kicker",
            ),
        ),
        migrations.AddField(
            model_name="articleauthorrelationship",
            name="article",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authors",
                to="articles.ArticlePage",
            ),
        ),
        migrations.AddField(
            model_name="articleauthorrelationship",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="core.StaffPage",
            ),
        ),
    ]
