# Generated by Django 2.0.9 on 2018-11-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("articles", "0004_auto_20180903_2035")]

    operations = [
        migrations.CreateModel(
            name="MigrationInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(db_index=True)),
                ("guid", models.CharField(max_length=255)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.ArticlePage",
                    ),
                ),
            ],
        )
    ]
