# Generated by Django 2.0.7 on 2018-07-19 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_kicker'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='kicker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.Kicker'),
        ),
    ]
