# Generated by Django 2.0.7 on 2018-07-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0040_page_draft_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("articles", "0008_auto_20180726_1915"),
    ]

    operations = [
        migrations.RenameModel(old_name="ArticlesIndex", new_name="ArticlesIndexPage"),
        migrations.AlterField(
            model_name="articlepage",
            name="featured_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown at the top of the article and on the home page.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtailimages.Image",
            ),
        ),
    ]
