# Generated by Django 2.0.8 on 2018-08-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("articles", "0009_auto_20180727_1437")]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="kicker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="articles.Kicker",
            ),
        )
    ]
