# Generated by Django 2.0.8 on 2018-08-18 18:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180818_1804'),
        ('articles', '0010_auto_20180817_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthorrelationship',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articleauthorrelationship',
            name='title',
        ),
        migrations.AddField(
            model_name='articleauthorrelationship',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.StaffPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleauthorrelationship',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='articles.ArticlePage'),
        ),
    ]
