# Generated by Django 2.0.8 on 2018-08-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("articles", "0011_auto_20180818_1807")]

    operations = [
        migrations.RenameField(
            model_name="articleauthorrelationship", old_name="person", new_name="author"
        )
    ]
