# Generated by Django 2.0.8 on 2018-08-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("articles", "0012_auto_20180818_1808")]

    operations = [migrations.RemoveField(model_name="articlepage", name="date")]
