# Generated by Django 2.0.8 on 2018-08-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("articles", "0013_remove_articlepage_date")]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="featured_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown at the top of the article and on the home page.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Photo",
            ),
        )
    ]
