language: python
matrix:
  include:
    - python: "3.6"
      dist: trusty
      sudo: true
    - python: "3.7"
      dist: xenial
      sudo: true

services:
  - docker

addons:
  postgresql: "9.6"
  
before_install:
  - pip install pipenv
  - npm install -g npm@"^6.4.0"

install:
  - pipenv install --dev
  - npm ci
  - npx webpack --config webpack.development.config.js
    
before_script:
  - pipenv check
  - black . --check --exclude node_modules/
  - flake8 --exclude node_modules/ || true
  - pipenv run pip freeze
  - psql -c 'create database pipeline;' -U postgres
  - pipenv run python manage.py makemigrations --check --dry-run
  - pipenv run python manage.py collectstatic

script:
  - pipenv run python manage.py test
  - docker-compose build
