# Generated by Django 2.1.4 on 2018-12-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="contributor", name="article_author"),
        migrations.AddField(
            model_name="articleauthor",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="articleauthor",
            name="staff_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.StaffPage",
            ),
        ),
        migrations.DeleteModel(name="Contributor"),
    ]
