# Generated by Django 2.1.4 on 2018-12-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20181225_2047")]

    operations = [
        migrations.RenameModel(old_name="ArticleAuthor", new_name="Contributor"),
        migrations.RemoveField(model_name="staffpage", name="article_author"),
    ]
