# Generated by Django 2.0.8 on 2018-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_auto_20180818_1535")]

    operations = [
        migrations.AlterModelOptions(
            name="position", options={"ordering": ["sort_order"]}
        ),
        migrations.AddField(
            model_name="position",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
