# Generated by Django 5.0.9 on 2024-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articlepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
