# Generated by Django 2.1.4 on 2018-12-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0004_auto_20181225_2058")]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="photographer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.Contributor",
            ),
        )
    ]
