# Generated by Django 5.0.9 on 2024-10-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kicker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
