# Generated by Django 2.2.1 on 2020-02-09 20:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200209_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniontimeline',
            name='events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(default='', required=True)), ('date', wagtail.core.blocks.RichTextBlock(default='', required=True)), ('body', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('tooltip', wagtail.core.blocks.RichTextBlock())], blank=True)), ('featured_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
