# Generated by Django 5.0.9 on 2024-10-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_blogpage_page_ptr_delete_blogindexpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='headline',
            field=models.CharField(blank=True, max_length=250, verbose_name='Headline'),
        ),
    ]
