# Generated by Django 5.0.9 on 2024-10-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_articlepage_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='headline',
        ),
    ]
