# Generated by Django 2.2.9 on 2020-01-31 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0007_auto_20200131_0036")]

    operations = [
        migrations.RemoveField(model_name="candidate", name="contributor"),
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="office",
                to="core.Office",
            ),
        ),
    ]
