# Generated by Django 2.2.5 on 2019-12-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20191130_1915"),
    ]

    operations = [
        migrations.RemoveField(model_name="articlepage", name="Form",),
        migrations.AddField(
            model_name="articlepage",
            name="Forms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.FormField",
            ),
        ),
    ]
