# Generated by Django 5.0.9 on 2024-10-09 21:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_articlepage_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='headline',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subdeck',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
