# Generated by Django 2.2.9 on 2020-01-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20200131_0038")]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="office",
                to="core.Office",
            ),
            preserve_default=False,
        )
    ]
