# Generated by Django 2.2.1 on 2020-02-20 22:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200209_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniontimeline',
            name='events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(default='', required=True)), ('date', wagtail.core.blocks.RichTextBlock(default='', required=True)), ('body', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph_before', wagtail.core.blocks.RichTextBlock()), ('tooltip', wagtail.core.blocks.StructBlock([('word', wagtail.core.blocks.RichTextBlock()), ('definition', wagtail.core.blocks.RichTextBlock())]))]))), ('featured_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
