# Generated by Django 5.0.9 on 2024-10-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_articlepage_headline_articlepage_subdeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='headline',
        ),
    ]
