# Generated by Django 2.0.8 on 2018-08-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20180831_1621")]

    operations = [
        migrations.RemoveField(model_name="photo", name="image"),
        migrations.RemoveField(model_name="photo", name="photographer"),
        migrations.DeleteModel(name="Photo"),
    ]
