# Generated by Django 2.2 on 2019-04-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20190429_2122")]

    operations = [migrations.DeleteModel(name="Photo")]
