# Generated by Django 5.0.9 on 2024-10-09 23:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_articlepage_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('photo', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['italic'], 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], 'help_text': 'Width of image in article.'}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('size', 3)]], {})}),
        ),
    ]
