# Generated by Django 5.0.9 on 2024-10-09 23:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('photo', 4), ('photo_gallery', 6), ('embed', 9), ('carousel', 10), ('blockquote', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['italic'], 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], 'help_text': 'Width of image in article.'}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('size', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'image'}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'URL to the content to embed.'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], 'help_text': 'Width of video in article.'}), 9: ('wagtail.blocks.StructBlock', [[('embed', 7), ('size', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('image', 1)]], {}), 11: ('core.models.BlockQuoteBlock', (), {})}),
        ),
    ]
