# Generated by Django 2.2.9 on 2020-01-31 02:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [("core", "0011_auto_20200131_0053")]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("election_site_id", models.IntegerField(default=-1)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.RemoveField(model_name="candidate", name="position"),
        migrations.AddField(
            model_name="candidate",
            name="election_in",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Election",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="office",
            name="election_in",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Election",
            ),
            preserve_default=False,
        ),
    ]
