# Generated by Django 5.0.9 on 2024-10-10 01:35

import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('rich_name', wagtail.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
