# Generated by Django 2.0.8 on 2018-08-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0012_auto_20180831_1724")]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="photographer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.StaffPage",
            ),
        )
    ]
