# Generated by Django 5.0.9 on 2024-10-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_articlepage_featured_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='kicker',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
