# Generated by Django 2.2 on 2019-05-01 16:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0014_auto_20190430_1628")]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="rich_name",
            field=wagtail.core.fields.RichTextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
