# Generated by Django 2.2 on 2019-05-01 17:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0015_auto_20190501_1640")]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="rich_name",
            field=wagtail.core.fields.RichTextField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="staff_page",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.StaffPage",
            ),
        ),
    ]
