# Generated by Django 2.2.9 on 2020-01-31 03:23

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_candidatepage_officesorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices_in', to='core.CandidatePage'),
        ),
    ]
