# Generated by Django 5.0.9 on 2024-10-10 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_articlepage_kicker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='kicker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kicker'),
        ),
    ]
