# Generated by Django 5.0.9 on 2024-10-11 00:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_articlepage_kicker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthorRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='core.articlepage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.contributor')),
            ],
            options={
                'unique_together': {('article', 'author')},
            },
        ),
    ]
