# Generated by Django 2.2 on 2019-05-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0016_auto_20190501_1716")]

    operations = [
        migrations.RemoveField(model_name="contributor", name="staff_page"),
        migrations.AddField(
            model_name="staffpage",
            name="contributor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Contributor",
            ),
        ),
    ]
