# Generated by Django 2.2 on 2019-05-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0017_auto_20190501_1738")]

    operations = [
        migrations.AlterField(
            model_name="staffpage",
            name="contributor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_page",
                to="core.Contributor",
            ),
        )
    ]
