# Generated by Django 2.2 on 2019-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0018_auto_20190502_1335")]

    operations = [
        migrations.AddField(
            model_name="term", name="acting", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="term", name="de_facto", field=models.BooleanField(default=False)
        ),
    ]
