# Generated by Django 5.0.9 on 2024-10-12 05:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staffindexpage_customimage_staffpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('acting', models.BooleanField(default=False)),
                ('de_facto', models.BooleanField(default=False)),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='core.staffpage')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='core.position')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
