# Generated by Django 5.0.9 on 2024-10-12 05:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='contributor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_page', to='core.contributor'),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage'),
        ),
        migrations.AlterField(
            model_name='term',
            name='person',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='core.staffpage'),
        ),
    ]
