# Generated by Django 5.0.9 on 2024-10-13 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_staffpage_contributor_alter_staffpage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage'),
        ),
    ]
