# Generated by Django 5.0.9 on 2024-10-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffindexpage',
            name='positions',
            field=models.ManyToManyField(blank=True, to='core.position'),
        ),
    ]
