# Generated by Django 2.2.9 on 2020-02-02 03:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_candidatepage_nominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionindexpage',
            name='panels',
            field=wagtail.core.fields.StreamField([('three_cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StructBlock([('candidate', wagtail.core.blocks.PageChooserBlock(page_type=['core.Office']))]))]))], null=True),
        ),
    ]
