# Generated by Django 5.0.9 on 2024-10-14 04:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_staffindexpage_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffindexpage',
            name='positions',
        ),
        migrations.AddField(
            model_name='staffindexpage',
            name='positions',
            field=wagtail.fields.StreamField([('position', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, help_text='Enter the positions that staff members can hold. The order matters.'),
        ),
    ]
