# Generated by Django 5.0.9 on 2024-10-14 05:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_staffindexpage_positions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='staffindexpage',
            name='positions',
            field=wagtail.fields.StreamField([('position', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Position',), {})}, help_text='Order matters. The first position is the most important.'),
        ),
    ]
