# Generated by Django 2.2.9 on 2020-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0027_auto_20200202_1822")]

    operations = [
        migrations.RemoveField(model_name="office", name="req_nominations"),
        migrations.RemoveField(model_name="officesorderable", name="electionPage"),
    ]
