# Generated by Django 2.2.9 on 2020-02-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200202_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatepage',
            name='name',
        ),
    ]
