# Generated by Django 2.2.9 on 2020-02-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0029_remove_candidatepage_name")]

    operations = [
        migrations.AddField(
            model_name="candidatepage",
            name="related_articles",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.ArticlePage",
            ),
        )
    ]
