# Generated by Django 2.2.9 on 2020-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0035_auto_20200215_2037")]

    operations = [
        migrations.AlterField(
            model_name="office", name="election_in", field=models.IntegerField()
        )
    ]
