# Generated by Django 3.2.9 on 2021-12-07 01:15

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200326_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#DA1E05', max_length=7),
        ),
    ]
