# Generated by Django 2.2.10 on 2021-10-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200326_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='title',
            field=models.CharField(default='person', max_length=255),
            preserve_default=False,
        ),
    ]
