# Generated by Django 3.2.9 on 2021-12-07 01:40

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_articlepage_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='color',
            new_name='header_color',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='background_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='font_color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7),
        ),
    ]
