# Generated by Django 2.2.10 on 2021-10-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_map'),
        ('core', '0037_auto_20200326_1525'),
    ]

    operations = [
    ]
