# Generated by Django 3.2.9 on 2021-12-07 02:20

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20211207_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='lightheader_color',
            field=wagtail_color_panel.fields.ColorField(default='#e0402b', max_length=7),
        ),
    ]
