# Generated by Django 2.2.10 on 2022-03-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220315_1510'),
        ('core', '0047_auto_20220326_0452'),
    ]

    operations = [
    ]
