# Generated by Django 2.2.10 on 2023-05-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20220327_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
    ]
