# Generated by Django 2.2.10 on 2023-01-24 01:43

import core.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks

def move_images(apps, schema_editor):
    ArticlePage = apps.get_model("core", "ArticlePage")
    for page in ArticlePage.objects.all():
        body = []
        found = False
        for child in page.body:
            if child.block_type == 'carousel':
                found = True
                NewCarouselValue = {'size': 'medium', 'images': []}
                for image in child.value:
                    NewCarouselValue['images'].append({'image': image['value'], 'caption': ''})
                stream_data.append({"type": 'carousel', "value": NewCarouselValue})
        if found:
            page.body = body
            page.save()
    print("Testing right now")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_delete_homepagecarouselitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('photo', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic'], required=False)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Width of image in article.'))])), ('photo_gallery', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['italic'], required=False))]), icon='image')), ('embed', wagtail.core.blocks.StructBlock([('embed', wagtail.embeds.blocks.EmbedBlock(help_text='URL to the content to embed.')), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Width of video in article.'))])), ('carousel', wagtail.core.blocks.StructBlock([('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size of carousel.')), ('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(classname='caption', required=False))])))])), ('blockquote', core.models.BlockQuoteBlock())], blank=True),
        ),
        migrations.RunPython(move_images),
    ]
