# Generated by Django 2.0.8 on 2018-08-03 18:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_authorsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='biography',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
