# Generated by Django 2.0.8 on 2018-08-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0040_page_draft_title"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("authors", "0004_authorpage_biography"),
    ]

    operations = [
        migrations.DeleteModel(name="AuthorPage"),
        migrations.DeleteModel(name="AuthorsIndexPage"),
    ]
