# Generated by Django 2.0.9 on 2018-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("newsletter", "0003_newslettersettings")]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersettings", options={"verbose_name": "newsletter settings"}
        )
    ]
