# Generated by Django 2.0.8 on 2018-08-31 17:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0040_page_draft_title")]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "featured_articles",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "one_column",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "two_columns",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "left_column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "right_column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "emphasize_column",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                ],
                                                help_text="Which article, if either, should appear larger.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "three_columns",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "left_column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "middle_column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "right_column",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "article",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            target_model=[
                                                                "articles.ArticlePage"
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "headline",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            help_text="Optional. Will override the article's headline.",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "recent_articles",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "num_articles",
                                            wagtail.core.blocks.IntegerBlock(
                                                help_text="Number of recent articles to display.",
                                                label="Number of articles",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
