# Generated by Django 2.0.7 on 2018-07-18 20:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0003_homepage_featured_article")]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_articles",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.core.blocks.PageChooserBlock(
                            target_model=["articles.ArticlePage"]
                        ),
                    )
                ],
                null=True,
            ),
        )
    ]
