# Generated by Django 2.2.10 on 2022-03-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220315_0114'),
        ('home', '0005_auto_20220315_0114 (copy)'),
    ]

    operations = [
    ]
