# Generated by Django 5.0.9 on 2024-10-11 20:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_featured_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_articles',
            field=wagtail.fields.StreamField([('one_column', 4), ('two_columns', 6), ('three_columns', 7), ('recent_articles', 9), ('hero', 4)], block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['core.ArticlePage']}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': "Optional. Will override the article's headline.", 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional. Overides the image on the post.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('article', 0), ('headline', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('column', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')], 'help_text': 'Which article, if either, should appear larger.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('left_column', 3), ('right_column', 3), ('emphasize_column', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('left_column', 3), ('middle_column', 3), ('right_column', 3)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of recent articles to display.', 'label': 'Number of articles'}), 9: ('wagtail.blocks.StructBlock', [[('num_articles', 8)]], {})}, null=True),
        ),
    ]
