# Generated by Django 2.0.8 on 2018-08-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0006_auto_20180819_2107")]

    operations = [
        migrations.RemoveField(model_name="homepage", name="featured_article")
    ]
