# Generated by Django 2.2.10 on 2022-03-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220315_1433'),
        ('home', '0008_auto_20220326_0452'),
    ]

    operations = [
    ]
