# Generated by Django 2.0.8 on 2018-10-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("R", models.IntegerField()),
                ("G", models.IntegerField()),
                ("B", models.IntegerField()),
            ],
        )
    ]
