# Generated by Django 2.1.4 on 2018-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("R", models.IntegerField(default=255)),
                ("G", models.IntegerField(default=0)),
                ("B", models.IntegerField(default=0)),
                (
                    "id",
                    models.IntegerField(
                        default=0, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        )
    ]
