# Generated by Django 2.0.8 on 2018-10-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lights", "0002_auto_20181003_0114")]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="id",
            field=models.IntegerField(
                default=0, editable=False, primary_key=True, serialize=False
            ),
        )
    ]
